### ISSUE TITLE
BIOS parameters

### ISSUE THREAD

**Issue by stefhenry** [fritsvt/Dell-Latitude-E5570-Hackintosh#1]
Hi,

is it possible to post the BIOS parameters you used?
I am experimenting a few issues during install.

Thanks

**Comment by fritsvt** [comment]
What issues are you experiencing?

**Comment by stefhenry** [comment]
I can't make the intel iGPU working with acceleration, system reports intel HD Graphic 620 with only 7MB of RAM...

**Comment by headshotde** [comment]
I got working Clover Bootpack for E5570 Catalina

**Comment by fritsvt** [comment]
@headshotde awesome! Do you mind sharing it? I'd love to update to Catalina and update the repo when I get it working.

Edit: just found out you already uploaded it in your repo so I'm going to try it out later this week. Feel free to open a PR if you want it in this repo.

**Comment by headshotde** [comment]
i can Upload it tomorrow, only need optimize CPU because battery drains to fast

**Comment by fritsvt** [comment]
Cool, do you also use the DW1830 for Wifi/Bluetooth?

**Comment by kieth1205** [comment]
could you help me to setup bios for install hackintosh? thanks

**Comment by fritsvt** [comment]
What problem are you having with the bios?

**Comment by kieth1205** [comment]
@fritsvt could you show check and uncheck box on bios? Some of them make me couldn't boot to hackintosh usb

**Comment by fritsvt** [comment]
What do you mean?
